# Generated by Django 3.2 on 2021-04-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fortuner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acceleration', models.IntegerField()),
                ('Braking', models.IntegerField()),
                ('gears', models.IntegerField()),
                ('Engine_Temperature', models.IntegerField()),
                ('Battery', models.IntegerField()),
                ('RPM', models.IntegerField()),
                ('Fuel_Burnt', models.IntegerField()),
                ('Distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Harrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acceleration', models.IntegerField()),
                ('Braking', models.IntegerField()),
                ('gears', models.IntegerField()),
                ('Engine_Temperature', models.IntegerField()),
                ('Battery', models.IntegerField()),
                ('RPM', models.IntegerField()),
                ('Fuel_Burnt', models.IntegerField()),
                ('Distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acceleration', models.IntegerField()),
                ('Braking', models.IntegerField()),
                ('gears', models.IntegerField()),
                ('Engine_Temperature', models.IntegerField()),
                ('Battery', models.IntegerField()),
                ('RPM', models.IntegerField()),
                ('Fuel_Burnt', models.IntegerField()),
                ('Distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seltos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acceleration', models.IntegerField()),
                ('Braking', models.IntegerField()),
                ('gears', models.IntegerField()),
                ('Engine_Temperature', models.IntegerField()),
                ('Battery', models.IntegerField()),
                ('RPM', models.IntegerField()),
                ('Fuel_Burnt', models.IntegerField()),
                ('Distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='XUV500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acceleration', models.IntegerField()),
                ('Braking', models.IntegerField()),
                ('gears', models.IntegerField()),
                ('Engine_Temperature', models.IntegerField()),
                ('Battery', models.IntegerField()),
                ('RPM', models.IntegerField()),
                ('Fuel_Burnt', models.IntegerField()),
                ('Distance', models.IntegerField()),
            ],
        ),
    ]
